name: Auto Release APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  dart-analyze:
    name: Dart Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup_flutter

      - name: Dart Analyze check
        run: dart analyze

  mandatory-tests:
    name: Mandatory Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup_flutter

  build:
    name: Build APK
    needs: [dart-analyze]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup_flutter

      - name: Build APK
        run: flutter build apk --debug

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-apk
          release_name: "Latest APK"
          files: build/app/outputs/flutter-apk/app-debug.apk
          body: ${{ env.BUILD_DATE }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}